<?php

return [
    'KPN' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'KPN',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'KPN-all' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'KPN-all',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
        'skip_fiber_filters' => true,
    ],
    'KPN-pairbonded' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'KPN-pairbonded',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Glasdraad' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'Glasdraad',
        'thirdparty_name' => 'Glasdraad',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Glaspoort' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'Glaspoort',
        'thirdparty_name' => 'Glaspoort',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'FiberFlevo' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'FiberFlevo',
        'thirdparty_name' => 'FiberFlevo',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'FiberNH' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'FiberNH',
        'thirdparty_name' => 'FiberNH',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Digitale Stad' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'Digitale Stad',
        'thirdparty_name' => 'Digitale Stad',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Fryslân Ring' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'Fryslân Ring',
        'thirdparty_name' => 'Fryslan Ring',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Breedband Loosdrecht' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'Breedband Loosdrecht',
        'thirdparty_name' => 'Breedband Loosdrecht',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Glasvezel Edam-Volendam' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'Glasvezel Edam-Volendam',
        'thirdparty_name' => 'Glasvezel Edam-Volendam',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Breedband Rivierenland' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'Breedband Rivierenland',
        'thirdparty_name' => 'Breedband Rivierenland',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Caiway' => [
        'class' => \App\Libraries\CaiwayNetworkDirect::class,
        'driver' => 'caiway',
        'name' => 'Delta',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Ziggo' => [
        'class' => \App\Libraries\ZiggoPostcodeCheckV2::class,
        'driver' => 'ziggo',
        'name' => 'Ziggo',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'T-Mobile-GOP' => [
        'class' => \App\Libraries\OdidoNetworkDirect::class,
        'driver' => 'odido',
        'variant' => 'GOP',
        'technology' => 'fiber',
        'name' => 'Odido-GOP',
        'active' => true,
        'queue' => 't-mobile',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
        'cache_ttl_error' => 180,
        'cache_ttl_no_coverage' => env('SPEEDCHECK_NO_COVERAGE_CACHE_TTL', 604800),
    ],
    'Odido-OPF' => [
        'class' => \App\Libraries\OdidoNetworkDirect::class,
        'driver' => 'odido',
        'variant' => 'OPF',
        'technology' => 'fiber',
        'name' => 'Odido ODF',
        'active' => true,
        'queue' => 't-mobile',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
        'cache_ttl_error' => 180,
        'cache_ttl_no_coverage' => env('SPEEDCHECK_NO_COVERAGE_CACHE_TTL', 604800),
    ],
    'Delta-odido' => [
        'class' => \App\Libraries\OdidoNetworkDirect::class,
        'driver' => 'odido',
        'variant' => 'DFN',
        'technology' => 'fiber',
        'name' => 'Delta-odido',
        'active' => true,
        'queue' => 't-mobile',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
        'cache_ttl_error' => 180,
        'cache_ttl_no_coverage' => env('SPEEDCHECK_NO_COVERAGE_CACHE_TTL', 604800),
    ],
    'Odido-kpn' => [
        'class' => \App\Libraries\OdidoNetworkDirect::class,
        'driver' => 'odido',
        'variant' => 'WBA',
        'technology' => 'fiber',
        'name' => 'Odido-kpn',
        'active' => true,
        'queue' => 't-mobile',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
        'cache_ttl_error' => 180,
        'cache_ttl_no_coverage' => env('SPEEDCHECK_NO_COVERAGE_CACHE_TTL', 604800),
    ],
    'Jonaz' => [
        'class' => \App\Libraries\JonazNetworkDirect::class,
        'driver' => 'jonaz',
        'name' => 'Fiber Crew',
        'speed' => 1000,
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'L2Fiber' => [
        'class' => \App\Libraries\GlasnetNetworkDirect::class,
        'driver' => 'glasnet',
        'supplier' => 'L2fiber',
        'name' => 'L2Fiber',
        'active' => true,
        'queue' => 'glasnet',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'EFiber' => [
        'class' => \App\Libraries\GlasnetNetworkDirect::class,
        'driver' => 'glasnet',
        'supplier' => 'EFiber',
        'name' => 'EFiber',
        'active' => true,
        'queue' => 'glasnet',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'GlaswebVenray' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'GlaswebVenray',
        'thirdparty_name' => 'Glasweb Venray',
        'planned_fiber_speed' => 1000,
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'HSLnet' => [
        'class' => \App\Libraries\GlasnetNetworkDirect::class,
        'driver' => 'glasnet',
        'supplier' => 'HSLnet',
        'name' => 'HSLnet',
        'active' => true,
        'queue' => 'glasnet',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'CAI Harderwijk' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'CAI Harderwijk',
        'thirdparty_name' => 'CAI Harderwijk',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'KTWaalre' => [
        'class' => \App\Libraries\KPN::class,
        'driver' => 'kpn',
        'name' => 'WeConnect Waalre',
        'thirdparty_name' => 'KTWaalre',
        'planned_fiber_speed' => 1000,
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'SKV' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'SKV',
        'project_tags' => [
            'skv_netwerk',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Citius Fiber Prinsenbeek' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Citius Fiber Prinsenbeek',
        'project_tags' => [
            'delta_prinsenbeek',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Fiberbuiten' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Fiberbuiten',
        'project_tags' => [
            'fiberbuiten',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Glasvezel De Wolden' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Glasvezel De Wolden',
        'project_tags' => [
            'glasvezel_de_wolden',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Glasvezel Helmond' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Glasvezel Helmond',
        'project_tags' => [
            'glasvezel_helmond',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Glasvezel Noord' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Glasvezel Noord',
        'project_tags' => [
            'glasvezelnoord',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Glasvezel Pekela' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Glasvezel Pekela',
        'project_tags' => [
            'glasvezel_pekela',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Glasvezel Zuidenveld' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Glasvezel Zuidenveld',
        'project_tags' => [
            'glasvezel_zuidenveld',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Herman Gorterlaan' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Herman Gorterlaan',
        'project_tags' => [
            'hgorterlaan',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'KempenGlas' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'KempenGlas',
        'project_tags' => [
            'kempenglas',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'MaasKantNet' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'MaasKantNet',
        'project_tags' => [
            'maaskantnet',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Midden-BrabantGlas' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Midden-BrabantGlas',
        'project_tags' => [
            'middenbrabantglas',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'KNN' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Fiber Operator',
        'project_tags' => [
            'knn_almere',
            'knn_deventer',
            'knn_dronten',
            'rf_ehv',
            'knn_enschede',
            'knn_haaksbergen',
            'knn_helmond',
            'knn_leeuwarden',
            'rf_meierijstad',
            'knn_middendrenthe',
            'knn_rijssen_holten',
            'rf_rosmalen',
            'rf_uden',
            'knn_vught',
            'knn_wierden',
            'rf_ypenburg',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Open Dutch Fiber' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Open Dutch Fiber',
        'speed' => 10000,
        'project_tags' => [
            'odf_ams_bijlmer',
            'odf_ams_boslomwp',
            'odf_ams_gaas',
            'odf_ams_slotermeer',
            'odf_assen',
            'odf_bvw_khsk',
            'odf_cadi_rkv',
            'odf_delft_west',
            'odf_dhng_laakstat',
            'odf_dhng_schilzeeh',
            'odf_dhng_trvkr',
            'odf_hrlm_zuidoost',
            'odf_hrlm_zuidwest',
            'odf_heerhugowaard',
            'odf_heerlen_zuid',
            'odf_hellevoetsluis',
            'odf_hillegom_lisse',
            'odf_kerkrade',
            'odf_leiden_zuid',
            'odf_leidschendam',
            'odf_oegstgeest',
            'odf_purmerend',
            'odf_ridderkerk',
            'odf_roosendaal',
            'odf_rot_charlois',
            'odf_rot_pralexnrd',
            'odf_rot_pral_zuid',
            'odf_rotterdam_hoogvliet',
            'odf_ruc_swil_sprn',
            'odf_utr_demeern',
            'odf_utr_noordoost',
            'odf_utr_noordwest',
            'odf_utrecht_zuid',
            'odf_venlo_zuid',
            'odf_voorburg',
            'odf_voorschoten',
            'odf_waalwijk',
            'odf_woerden',
            'odf_ztrm_noord',
            'odf_ztrm_zuid',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Primevest' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Primevest',
        'project_tags' => [
            'pif_denhaag',
            'pif_ehv',
            'pif_rotterdam',
            'pif_rotterdam_ijsselmonde',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'RE-NET Hoogeveen' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'RE-NET Hoogeveen',
        'speed' => 1000,
        'project_tags' => [
            'renet_hoogeveen',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Rotterdams Glasvezel' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Rotterdams Glasvezel',
        'project_tags' => [
            'rotterdamsglasvezel',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Stille Wille' => [
        'class' => \App\Libraries\HgvtNetworkDirect::class,
        'driver' => 'hgvt',
        'name' => 'Stille Wille',
        'project_tags' => [
            'stillewille',
        ],
        'active' => true,
        'queue' => 'hgvt',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'SKP' => [
        'class' => \App\Libraries\SkpNetworkDirect::class,
        'driver' => 'skp',
        'name' => 'SKP',
        'cities' => ['NOOTDORP', 'PIJNACKER', 'DELFGAUW'],
        'nonce' => env('SKP_NONCE', 'f803c3e245'),
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'Kabelnoord' => [
        'class' => \App\Libraries\KabelnoordNetworkDirect::class,
        'driver' => 'kabelnoord',
        'name' => 'Kabelnoord',
        'active' => true,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
    'BroFiber' => [
        'class' => \App\Libraries\FiberNlNetworkDirect::class,
        'driver' => 'fibernl',
        'network' => 'BroFiber',
        'name' => 'BroFiber',
        'speed' => 1000,
        'active' => false,
        'queue' => 'default',
        'cache_ttl' => env('SPEEDCHECK_CACHE_TTL', 43200),
    ],
];
